# Configuración de Netlify para PhoneSpot E-Commerce

[build]
  # No hay proceso de build para frontend estático
  command = "echo 'PhoneSpot E-Commerce - Frontend conectado a Railway.app'"
  publish = "."
  
[build.environment]
  NODE_VERSION = "18"
  # ✅ Backend de Railway (ya configurado en JavaScript/config.js)
  BACKEND_URL = "https://phonespot-backend-production.up.railway.app/api"

# Variables de entorno para el frontend
# (El backend está en Railway.app: https://phonespot-backend-production.up.railway.app)

# Context-specific deploy settings
[context.production]
  command = "echo 'Deploying production build'"

[context.deploy-preview]
  command = "echo 'Deploying preview build'"

# Headers para caché y seguridad
[[headers]]
  for = "/*"
  [headers.values]
    # Cache control
    Cache-Control = "public, max-age=0, must-revalidate"
    
    # Seguridad
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache para assets estáticos (CSS, JS, imágenes)
# ⚠️ Cache reducido para permitir actualizaciones más rápidas
[[headers]]
  for = "/style*.css"
  [headers.values]
    Cache-Control = "public, max-age=3600, must-revalidate"

[[headers]]
  for = "/JavaScript/*.js"
  [headers.values]
    Cache-Control = "public, max-age=3600, must-revalidate"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=3600, must-revalidate"

[[headers]]
  for = "/IMG/*"
  [headers.values]
    Cache-Control = "public, max-age=86400, immutable"

# Redirects para navegación
[[redirects]]
  from = "/admin"
  to = "/HTML/admin.html"
  status = 200

[[redirects]]
  from = "/carrito"
  to = "/HTML/Carrito.html"
  status = 200

[[redirects]]
  from = "/login"
  to = "/HTML/login.html"
  status = 200

[[redirects]]
  from = "/registro"
  to = "/HTML/registro.html"
  status = 200

# Redirect 404 a la página principal
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404

